org.gradle.jvmargs=-Xmx2G -Djava.net.preferIPv4Stack=true
org.gradle.daemon=true
org.gradle.parallel=true

minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.21.9)
neo_version=21.8.53
loader_version_range=[1,)

mod_id=raccoon
mod_name=Minecraft Raccoon
mod_license=MIT
mod_version=1.2.2
mod_group_id=com.raccoon
